#!/bin/bash
cd /tmp
mkdir -p ~/.config/rclone
echo "$rclone_config" > ~/.config/rclone/rclone.conf
echo "Started upload daemon"
date +%c
sleep 30m

com () 
{ 
    tar --use-compress-program="pigz -k -1 " -cf $2.tar.gz $1
}

while :
do
a=$(curl --silent https://raw.githubusercontent.com/SuperCosmicBeing/variables/master/upload)
echo $a

if [ $a = "yes" ]; then
        echo "Compressing and uploading ccache!"
        time com ccache bliss
        time rclone copy bliss.tar.gz gdrive:ccache -P
        date +%c
        sleep 22m
else
        echo "Skipped Uploading Ccache"
        sleep 25m
fi
done

